### ISSUE TITLE
Location Accuracy

### ISSUE THREAD

**Issue by byroncoetsee** [benzamin/BBLocationManager#2]
Hey there,

Thanks for the library :)

Question: After I've set my desired accuracy, can I be guaranteed the any time I call getCurrentLocation, the returned location will have that accuracy?
If not, is there a way to retrieve the current accuracy?

Thanks

**Comment by benzamin** [comment]
Hey Byron,
Thanks for your interest in BBLocationManager. 

The accuracy is totally dependent on Apple's location service Core. BBLocationManager is just a easy-to-use wrapper over the Apple's CoreLocation library. So when you set the accuracy, BBLocationManager send your instructions to CoreLocation library, the rest depends on the CoreLocation library. See details here: https://developer.apple.com/documentation/corelocation/cllocationmanager/1423836-desiredaccuracy

But you can easily test the accuracy, just install the BBLocatiobnManager example app to your iPhone and try to see your location on Map(zoom in/out of needed), and you can easily guess the accuracy level.

Thanks, let me know if you have any more question.
Ben.
