### ISSUE TITLE
Location issue in region

### ISSUE THREAD

**Issue by nileshordex** [benzamin/BBLocationManager#3]
I was tried to add two nearest location but it was not allowed. When i was tried this instead of add two location it is display message below message.

**Log for issue.**
[BBLocationManager] Fence already exist for area: 9,Pin-Up Bowl ---- inside: Restaurant_2
2018-02-09 17:04:53.593570+0530 demo[67141:434050] Added GeoFence: {
    BBeventTimeStamp = "09-02-2018 17:04:53";
    BBeventType = BBFenceEventRepeated;
    BBfenceCoordinate =     {
        BBRadious = 100;
        latitude = "38.65574645996094";
        longitude = "-90.2991943359375";
    };
    BBfenceIDentifier = "Restaurant_2";
}
2018-02-09 17:04:53.657464+0530 demo[67141:434050] [BBLocationManager] Fence already exist for area: (null) ---- inside: Restaurant_2
2018-02-09 17:04:53.657959+0530 demo[67141:434050] Added GeoFence: {
    BBeventTimeStamp = "09-02-2018 17:04:53";
    BBeventType = BBFenceEventRepeated;
    BBfenceCoordinate =     {
        BBRadious = 100;
        latitude = "38.65574645996094";
        longitude = "-90.2991943359375";
    };
    BBfenceIDentifier = "Restaurant_2";
}

==>
check below for location if first 5 digits same then doesn't allow first location every time used second location .
{
    lat = "38.655743";
    lng = "-90.29864";
    restID = 7;
    restoName = "Restaurant_1";
},
{
    lat = "38.655746";
    lng = "-90.29919";
    restID = 9;
    restoName = "Restaurant_2";
}

**Comment by benzamin** [comment]
Hey Nilesh,

Thanks for your interest in BBLocationManager. I can see that you added the first fence with a 100 meter radius, and trying to add another one nearest to it, which is approximately 50meter far from the previous one, thats why the fence is not working. Try to add fence with a short radius (which might cause problem to identify the fence exactly), or add a fence bit far from the previous one. Check out the Google Maps screenshot below.
<img width="1303" alt="screen shot 2018-02-11 at 12 05 24 am" src="https://user-images.githubusercontent.com/3830968/36070546-eebefccc-0f26-11e8-90d4-73042ef3df01.png">

Hope you understand, let me know if you have anymore questions.

Benzamin.

**Comment by nileshordex** [comment]
@benzamin 

Thank's Dear i hope your are well and great reply.
