### ISSUE TITLE
How to delete all GeoFence without any fenceInfo pass

### ISSUE THREAD

**Issue by nileshordex** [benzamin/BBLocationManager#4]
@benzamin 

Please help me for how to delete all GeoFence without any fenceInfo pass remove all data when every new location get.

**Comment by benzamin** [comment]
Use one of these 3 methods:

1. -(void)deleteCurrentFences;
Delete all the fences which are currently active. Those fences we created and are currently active, delete all of'em.

 2. -(void)deleteGeoFence:(BBFenceInfo*)fenceInfo; 
Deletes a geofence at a location, using the FenceInfo object. It searches for the  identifiers of the added fences based on fenceInfo, and deletes the desired one.

 3. -(void)deleteGeoFenceWithIdentifier:(NSString*)identifier; 
Deletes a geofence with a identifier. It searches for the  identifiers of the added fences, and deletes the desired one.

Hope this helps, thanks.

**Comment by nileshordex** [comment]
@benzamin 

Thank you so much dear i was implemented it is working fine.
