### ISSUE TITLE
It is not work  when app is in background.

### ISSUE THREAD

**Issue by JacobVinu** [benzamin/BBLocationManager#8]
I am developing an app that work in background. I add a geofence and put the app in background. After that BBLocationManagerDidEnterFence method will not work. Why? Is it doesn't work in background mode?

**Comment by JacobVinu** [comment]
I am developing an app that work in background. I add a geofence and put the app in background. After that BBLocationManagerDidEnterFence method will not work. Why? Is it doesn't work in background mode?

**Comment by benzamin** [comment]
When in the background, if a geofence is entered or exited, the app will come silently to foreground to execute the code written inside the geofence enter/exit trigger method. But the execution of the method is limited to certain features and time. How you are writing the code? If you do a network/API call it will work, you can also fire a local notification. But if you want to show a alert, it wont work. 

Hope this helps, if you still have some confusion, please provide some example code.

**Comment by JacobVinu** [comment]
I want to call an API when the user geofence is entered or exited. And also trigger a local notification. If the user start the navigation and put the device in pocket and travel, how can we call the API when user geofence is entered or exited? is there any solution?

**Comment by benzamin** [comment]
Its easy to add API calls when a fence is entered or exited in the background.

First make sure you have set up everything, including the info.plist keys(refer the documentation). Then implement the _BBLocationManagerDelegate_ protocal add your API calls + Local notification in the following methods:

```
-(void)BBLocationManagerDidEnterFence:(BBFenceInfo *)fenceInfo
-(void)BBLocationManagerDidExitFence:(BBFenceInfo *)fenceInfo
```

Refer to the sample app included in the project for details

**Comment by benzamin** [comment]
@JackobVinu Did u do the implementation correctly? If so please close ghe issue. Otherwise let me know if you have any further query.
